### ISSUE TITLE
Gas probleme

### ISSUE THREAD

**Issue by FloUz-ai** [ProjectOpenSea/seaport-js#101]
Hi, 

I am getting this error when trying to buy an order . It seems to struggle with gas: 

```cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="execution reverted", method="estimateGas", transaction={"from":"0x9f3752cd801fD513dAD4200aD08EA6b9d149C6Cd","to":"0x00000000006c3852cbEf3e08E8dF289169EdE581","value":{"type":"BigNumber","hex":"0x12795f58d50000"},"data":"0xfb0f3ee1000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000```

. I am using truffle/hd wallet. Any idea where it could come from?

**Comment by jpbm** [comment]
Getting the same error using ethers, following the exact code in the documentation. Apparently the error can mask another, underlying error: since the gas estimation simulates the transaction, it will fail if the transaction fails. 

The code below replicates the error (wallet address, api key, and private key are hidden here). Filename is *.mjs

`
import { Seaport } from "@opensea/seaport-js";
import { ethers } from "ethers";

// Provider must be provided to the signer when supplying a custom signer
const provider = new ethers.providers.JsonRpcProvider(
    "https://eth-mainnet.g.alchemy.com/v2/ALCHEMY_API_KEY"
);

const signer = new ethers.Wallet("WALLET_PRIVATE_KEY", provider);

const seaport = new Seaport(signer);

const offerer = "WALLET_ADDRESS";

const { executeAllActions } = await seaport.createOrder(
    {
      offer: [
        {
          amount: ethers.utils.parseEther("0.001").toString(),
          // WETH
          token: "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2",
        },
      ],
      consideration: [
        {
          itemType: 2,
          token: "0x8a90cab2b38dba80c64b7734e58ee1db38b8992e",
          identifier: "1",
          recipient: offerer,
        },
      ],
    },
    offerer,
    
);

const order = await executeAllActions();
`

**Comment by DEREK-DEV-AFK** [comment]
I am also getting same error of
` reason: 'cannot estimate gas; transaction may fail or may require manual gas limit',
  code: 'UNPREDICTABLE_GAS_LIMIT',`
I don't know what is an error here 
`const { Seaport } = require("@opensea/seaport-js");
const { ethers } = require("ethers");
const { data } = require("./details.json");

// Provider must be provided to the signer when supplying a custom signer
const provider = new ethers.providers.JsonRpcProvider(
    data.apiKey.goerli.infura.url
);

const signer = new ethers.Wallet(data.accounts.acc1["private-key"], provider);

const seaport = new Seaport(signer);
/// offering nad fullfillin it
const offerer = data.accounts.acc1.address;
const fulfiller = data.accounts.acc2.address;
async function main() {
    console.log("creating order !");
    const { executeAllActions } = await seaport.createOrder(
        {
            offer: [
                {
                    itemType: 2,
                    token: data.contract.goerli.nft,
                    identifier: "0",
                },
            ],
            consideration: [
                {
                    amount: ethers.utils.parseEther("0.1").toString(),
                    recipient: offerer,
                },
            ],
        },
        offerer
    );
    console.log("created order success");

    const order = await executeAllActions();
    console.log("order : ", order)

    const { executeAllActions: executeAllFulfillActions } =
        await seaport.fulfillOrder({
            order,
            accountAddress: fulfiller,
        });

    const transaction = await executeAllFulfillActions();

    console.log("transaction success");
    console.log(transaction);
}

main();`

**Comment by DEREK-DEV-AFK** [comment]
I have solved that problem by changing the provider and sometimes it runs but sometime it doesn't.
