### ISSUE TITLE
Difference seaport js Vs Open Sea Js 

### ISSUE THREAD

**Issue by FloUz-ai** [ProjectOpenSea/seaport-js#99]
Hi OpenSea, 

I want to do transaction to list NFTs and fufillOrders. 

It is not reallly clear to me which library should I use for that. It seems than opensea js does the job, but seaport could do it as well.. 

Pb, there is no field for the Opensea key in its instance .. what is strange. 

Could you please make it a bit clearer.. thanks in advance ?

**Comment by nfts4f4fff** [comment]
hey. Thats a good question. Opensea interacts with a different contract then seaport. When i list a nft it interacts with a totally different contract then seaport

**Comment by dineshtiwari69** [comment]
So Seaport is a NFT Marketplace Contract which means anyone can use seaport to create their own marketplace . 

Opensea uses seaport for it's marketplace. 
Every marketplace has a Conduit Contract responsible for the transfers. 
Opensea has it's own conduit . 

Opensea-JS helps index your signature orders so that it gets displayed in Opensea . Thus it requires Opensea API's. 

If you try to sell an order through seaport-js , opensea wont know anything about it . 

If you are dedicated to listing in Opensea , then use opensea-js . 

I hope that's clear . This is what i know so far from going through docs over and over again.

**Comment by nfts4f4fff** [comment]
I wanna list a nft on opensea using seaport. Opensea doesnt allow you to list multiple nfts in one signature. Thats why i and other people are using seaport.

**Comment by nfts4f4fff** [comment]
And i am right. Opensea.js is a JavaScript library for crypto-native ecommerce: buying, selling, and bidding on any cryptogood. With OpenSea.js, you can easily build your own native marketplace for your non-fungible tokens, or NFTs. These can be ERC-721 or ERC-1155 (semi-fungible) items. You don't have to deploy your own smart contracts or backend orderbooks. How that seaport.js help building your own marketplace ? It doesnt. Its mainly for interacting with opensea. It uses the opensea order flow.

**Comment by FloUz-ai** [comment]
hum ... I went through the doc several times, but I don't get how it works and what we shoud use to interact with opensea ? do u have any clue where I could find further explanation?

**Comment by sunwrobert** [comment]
Use `opensea-js`. The explanation @dineshtiwari69 should suffice

**Comment by FloUz-ai** [comment]
Yeah all good I went through the doc again, and read some discussion about seaport. Then I understood the example, and that's perfect, I think I've got the basics.

That's just strange that opensea does not see the listing when they are validate ...
